### ISSUE TITLE
How do I get an API KEY?

### ISSUE THREAD

**Issue by jesuejunior** [cognitedata/datapoints-csv-extractor#6]
I'd like to suggest some improvements to this and other libraries from cognitive, but all of them need the API KEY, is there one to use in a demo mode?

Thanks

**Comment by eventh** [comment]
Hi @jesuejunior, that would be really cool!
You can get an API KEY that gives you access to Cognite at this page: https://openindustrialdata.com/
This would only be a read-only key unfortunately.

**Comment by jesuejunior** [comment]
Hi @eventh, thanks a lot.
I think RO will be enough to run the tests.
